### PR TITLE
add pip check

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just as a trust-but-verify exercise... I guess there's no need to actually merge this (can just be included in the next release), but `pip check` does help keep the rest of the ecosystem working. This is _particularly_ important for anything that touches `pyls`, which has a history of getting `parso`, `jedi` and `ujson` screwed up, and failing mysteriously at runtime when it gets to using `pkg_resources`... of course it's not "Your Problem" if an upstream goes off and makes incompatible releases, but the more (automated!) eyes we can keep on this stuff, the better...

### CODE REVIEW

**Comment by marimeireles** [comment]
Ahhh sorry i didn't understand you needed pip check here. Thanks!

**Comment by bollwyvl** [comment]
I don't _need_ it... i'm just exhausted from trying to keep complex things from failing for reasons we can relatively easily avoid. For example, jupyter-lsp is a kind of _ridiculous_ environment, and every little bit counts in keeping it working properly for end users, but we kind of can't pass the buck and say, "the plugin is the problem, stop bothering us", so we _need_ to test plugins, etc.

**Comment by bollwyvl** [comment]
`pip check` is certainly fallible in its own right, as `pip` isn't without dependencies that _might_ come back with false negatives... and then there's stuff due to the shortcomings of wheels which lead to things that can fail (see `psycopg2-binary`, `ujson`, etc) but it's the best we have today.

**Comment by marimeireles** [comment]
Hahaha I see
Super fair :)
Thanks for the PR

**Pull request merged**
